trigger: none

pool: Docker-VM_Pool

stages:
  - stage:
    displayName: Scanning Stage
    jobs:
    - job: 
      displayName: Scanning
      continueOnError: true
      steps:
      - task: PowerShell@2
        displayName: Biome Lint
        continueOnError: true
        inputs:
          targetType: 'inline'
          script: |
            Invoke-WebRequest -Uri "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.3.8/biome-win32-x64.exe" -OutFile "$(Agent.ToolsDirectory)/biome.exe"
            $(Agent.ToolsDirectory)/biome.exe lint $(System.DefaultWorkingDirectory)/home/ubuntu/agent/_work/_tool/biome.exe lint . 
      
      - task: PowerShell@2
        displayName: 'Checkov Terraform Security Scan'
        continueOnError: true
        inputs:
          targetType: 'inline'
          script: |
            /home/azureuser/.local/bin/checkov -d "$(System.DefaultWorkingDirectory)" --framework terraform
      - task: PowerShell@2
        displayName: "Gitleaks Secret Scan"
        inputs:
          targetType: 'inline'
          script: 'gitleaks detect --source "$(System.DefaultWorkingDirectory)" --redact --exit-code 1'
      
      - task: PowerShell@2
        displayName: "Tfsec Terraform Security Scan"
        continueOnError: true
        inputs:
          targetType: 'inline'
          script: 'tfsec "$(System.DefaultWorkingDirectory)"'