trigger: none

pool: Docker-VM_Pool

stages: 
  - stage: Terraform_Initial_Validation
    displayName: Initial
    jobs:
    - job: 
      displayName: Terraform Initial
      steps:
      - task: TerraformInstaller@1
        displayName: Install
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        displayName: Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/Dev'
          backendServiceArm: 'Docker-VM-Connection'
          backendAzureRmOverrideSubscriptionID: '0f8f3a03-1fbc-4587-9442-3a42f6948e4e'
          backendAzureRmResourceGroupName: 'rg-terraform-state'
          backendAzureRmStorageAccountName: 'bkstterraformstate'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'infracodestate.tf'
      
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/terraform'
          artifact: 'terraform-configuration'
          publishLocation: 'pipeline'

      - task: TerraformTask@5
        displayName: Validation
        inputs:
          provider: 'azurerm'
          command: 'validate'
      
      - task: TerraformTask@5
        displayName: Plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: 'Docker-VM-Connection'
          environmentAzureRmOverrideSubscriptionID: '0f8f3a03-1fbc-4587-9442-3a42f6948e4e'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/Dev'
          commandOptions: '-out=$(System.DefaultWorkingDirectory)/tfplan'
  - stage: Terraform_Code_Scannig
    displayName: Scanning Stage
    dependsOn: Terraform_Initial_Validation
    jobs:
    - job: 
      displayName: Scanning
      continueOnError: true
      steps:
      - task: PowerShell@2
        displayName: Biome Lint
        continueOnError: true
        inputs:
          targetType: 'inline'
          script: |
            Invoke-WebRequest -Uri "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.3.8/biome-win32-x64.exe" -OutFile "$(Agent.ToolsDirectory)/biome.exe"
            $(Agent.ToolsDirectory)/biome.exe lint $(System.DefaultWorkingDirectory)/home/ubuntu/agent/_work/_tool/biome.exe lint . 
      
      - task: PowerShell@2
        displayName: 'Checkov Terraform Security Scan'
        continueOnError: true
        inputs:
          targetType: 'inline'
          script: |
            /home/azureuser/.local/bin/checkov -d "$(System.DefaultWorkingDirectory)" --framework terraform
      - task: PowerShell@2
        displayName: "Gitleaks Secret Scan"
        inputs:
          targetType: 'inline'
          script: 'gitleaks detect --source "$(System.DefaultWorkingDirectory)" --redact --exit-code 1'
      
      - task: PowerShell@2
        displayName: "Tfsec Terraform Security Scan"
        continueOnError: true
        inputs:
          targetType: 'inline'
          script: 'tfsec "$(System.DefaultWorkingDirectory)"'
  - stage: Approval
    displayName: "Production Approval"
    dependsOn: Terraform_Code_Scannig
    jobs:
    - job: 
      displayName: "Production Approval"
      pool: Server
      timeoutInMinutes: 140
      steps:    
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'yadavbrijendra20091994@gmail.com'
          instructions: 'Please review the Terraform Plan artifact. Approve only if the Terraform changes are expected.'
  - stage: Publish_Artifact
    displayName: Publish Artifact
    dependsOn: Approval
    condition: succeeded ()
    jobs:
    - job:
      displayName: "Publish Terraform Plan Artifact"
      steps:
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/tfplan'
          artifact: 'terraform-plan'
          publishLocation: 'pipeline'
